apiVersion: v2
description: A currently closed source, but hopefully soon to be open-source Ethereum
  Consensus layer client, written in Rust.
home: https://sifrai.com
icon: https://github.com/sifraitech/grandine/blob/master/gui.png
maintainers:
- email: busa.barnabas@gmail.com
  name: barnabasbusa
name: grandine
sources:
- https://github.com/sifraitech/grandine
type: application
version: 0.1.2
